language: minimal
services:
- docker
script:
- git clone https://github.com/lightningnetwork/lnd.git
- docker build -t lnd:latest lnd
- docker build -t lnd:latest .
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: bgJv9ZK2nSi6YZHHAg0/XKShIkLgJmun4c1k8jO+/v5wX9OW9XOPri6lY3maPkebx+ZVB9PryykBsqYSP0vGd6eFVSO8TApYL2VixCC5CPMN873r9aY/Dw1IJvn8VsfidXv969birb1BnGm3ZBvLNrBRbGxNH9cLtDVN0FipY6XqAGL/MinPrHkWuN70VhbGLhqwa4L/apS1CFT6NxCtEVLV8jsWtW+XdKmuFeci6faj3QZZ6juBLcXAk3ZjAcSzeX+wQQyAFYYpRu+jYRlLv9MhSQ/jcG0QuODjUnml1iQ8i67j7BLoxmVKvCO8DIR/Mw9dznhx7doMXPrp/JLumbH14YHH/mZbxmGs8L7eoR/jvMBr8ncWj9BYf+z7zGMzm7Ht+GqihHWYE2UkIjTqPefuzsivtBQsQ94e4eP9SCcR1OGxlwkCF4QhMxEkaaWEmp5vd2/3kw9A9VjHvbAaLvr+9sLb26BSiE4766x3I7S+4zEhfAv8iv9IBq3VBtOvmhZXCfW5miDKRFuXfvDSN2grgGJPXqxRd5o2C8Udql4OZhvSyxqAUstdYYXdqsIPTOXqlvXFl4LXG35ddym2Er7YZUm7rh+d1ETUdBGyigyZQFFgXc4yxiEG1MWV7IzPA6gFyWt0JvB9KokljMCiSQNjt6frFDd4fUqchk5ewxs=
  - secure: ZuzKvSO+DX3v+BTIEBFwvKLvqoCMvZLhfRSz+IX1F7O4pq4ngNmP5w6SlMGBsndaoOEyow35gOjP8YQRcH1wZ0SH65tSOyx4anhs2VQqfG+aIPJpgblWFRPgcNvFtjYWtL2n8mhcLMcL87nhPPrze0SC6/4tBguxavEZrN2d6FyGGztHjy8/t8emv/dsoM6Y/Dyj+KGCLUNsqgvmbtwlHO6YafuSIiEaiCZrCniED+R5nFQYuhv+iSI/w4vfBN7GZm1NS08/9xpESlE+lD+N7nEUAYM+P+73ptEykbvqLZEcFq+WX08jb0XZoobKrwfh5jqM+FwshGzgfDXnHgt7KKOqcGSbR1GlcFBe/nw4cMx4Uuhn5j4pmnrUSKclEZvPqVPiXKS8DA7KsN6Z4ElIBZJ9lsAnjs3wkuk6twgpXqab0KpaQ6JX7wPGR9PWtxtxU/JZpKcizJseAtbLrJmEIL0DnttstjMZjno9N3OFoPl0Gtf6490Bm6cc71WNtNMobeAMFwXnF2O/7oTEZ0Q1mKp5GaJ9bmCjhmVdTG5jxUfw04BtUji/szxvpNB9MBKRm+6kI0k47M4+3VDawfpJFMdB6kvVI+VsjSLy8bPhhyMan9Qy+d7t+AobzrNxBckg09CVKdr88hCKGlw+5Les5PM4Gtce5IVBNxzpSSbp5BY=
