sudo: true
dist: trusty

jobs:
  include:
    - stage: build lnd docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - ./travis-build-command.sh
      - docker push fuzzle/lnd

