language: minimal

services:
  - docker

script:
- git clone https://github.com/lightningnetwork/lnd.git lnd-source
- docker build -t lnd:latest lnd-source
- docker build -t tylevine/lnd:latest lnd-ext

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tylevine/lnd:latest
  on:
    branch: master

