language: minimal

services:
  - docker

env:
  global:
    secure: "KHOnUg/16oLTWvyFfwqUHh0sLt17NaJqxPH0k0Q63SU+fX6vnTsKUioO11ZY4dpL/MAcJjrSPI/rxnsnDKDD4x7HvYg0sReUlzGciwH46tcCJ6OPFezcbtXl5WKSeGRXHL4mN1oVIMLcTgRr7HvQVnJlSheHreSgNOH/tjSKPAqqjZWfKt0fnJaryzN7+0yfFXjuveqNCQz29k40QPDwiftfrDkieuFRd+V9CrTVlulVLypb/g3+o16EJWzNWXqrXqskrr5Dyulo2V7E53D3EB/ZoFKFksnxXd4SR7z1dtPe+e7Pd5a42zhz5J/IoGfJaUnDsfSrV4GyA7902VQt3JdoHb2Le7c0fmWRcsK7Y7nhDg9JJPlopWOKooqZUKPqH1gGleOqkS8iYmY2tZIJKL1XNuSwOtYL+/OFjeaxfjP4swj/BU8pBFcvmE33yXTzl1A377BmWDGNO+2uPQFkks1bvp363DRpSrh7IWGWfpy/G0hvb8hciw88rKM1T03+6KSzLLsxQIi5TPK2UrJBNskCxBG2KQ2oB8DHfADZMPFcBQARRqpXvuIa0+HtYAO6tEUblCMsUFR+u6+d/xQriOmCBaSXjoOnvU+UsB8LS6W+i88pgLSDPZyBE0jRSx0bdKjmj6UJ0h7kr3v5HmJwiEQt88m/rx0OlsEDbHHkw/0="
    secure: "Php8qyYeAnwTPtJF7U9rbVur1a5XIHbNdrc5Njr7oSTUbbwd+OtpaYC4z8+LcGPJjfJZq5a0l1GfrZYFvRA4KObo7FwXNdlWVS+RNs1AjeU6pft0dEpHQvZlAdmwGXKYbCSYrlJYkdJLF39tlyF/vZh0XVamzMqNvlmkXdvysIvX/SCHsjHrmpXM2VqOOweZo1kN6xhX0oJsIjwOWwQfvZPVxHKeCHErnlLnwR8nZ5ZrJ+citQI2jqVftLO3wFiXoESZhFsRYngriNBWOTDWbpoaAgcX+k/gN+n7kCTJI+D0av/8BrbLShX3dUDIYyTGoqYIDtSx0wNMVrEsIArfsSwRdckeNIlJ2l4AZ0a01ZSBdBGXwYF16PMK7iTxJpOmfUr9TrBVZb8SULuPmunRktvlkgxXw5AL7T70pHuZgDQ7gxmObTu9HcAeq05zvd659L8mfFwpPgsm1RaTu9fA3LMIL8bHRetJJaL0zC3OFNVq2eiAFRAH3z1TROI+NUb1CZHVasJfKR8QGkHbk6DUpVOqPyI3uX0ZVYHmV6BiycaBmSZPIaoCGryVjiKU8qEdFUn61/R5Iz5wXprkAoGoX5KcQzIP7XRueOdPC1oYypZeyGBJanEfoQIzaaxFjgy0toaxCuP0BejObz4DaTUU4mZOe659bREGbts9WrmxdUI="

script:
- git clone https://github.com/lightningnetwork/lnd.git
- docker build -t lnd:latest lnd
- docker build -t tylevine/lnd:latest .

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tylevine/lnd:latest
  on:
    branch: master

