language: minimal

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./lnd/travis-build-command.sh
  - ./lnd-ext/docker-build-command.sh
  - docker push tylevine/lnd
  - docker push tylevine/lnd-ext

