sudo: true
dist: trusty

jobs:
  include:
    - stage: build lnd-ext docker image
      before_script: cd lnd-ext
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - ./docker-build-command.sh
      - docker push fuzzle/lnd-ext
