version: '2.1'

services:
  bitcoind:
    container_name: bitcoind-testnet
    image: ruimarinho/bitcoin-core:0.16.0-alpine
    networks:
      btc_lightning_net:
        ipv4_address: ${BITCOIND_IPV4:-172.19.1.110}
    volumes:
      - 'bitcoin-data:/home/bitcoin/.bitcoin'
    command: -printtoconsole -testnet -txindex -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28332 -rpcbind=0.0.0.0 -rpcallowip=${RPCALLOWIP:-172.19.1.0/24} -rpcuser=${RPCUSER:-foo} -rpcpassword=${RPCPASSWORD:-bar}
    restart: "unless-stopped"

  lnd:
    container_name: lnd
    image: fuzzle/lnd-ext:latest
    networks:
      btc_lightning_net:
        ipv4_address: ${LND_IPV4:-172.19.1.120}
    ports:
      - 9735:9735
    volumes:
      - 'lnd-data:/root/.lnd'
    environment:
    - NOENCRYPTWALLET=y
    - ALIAS=${ALIAS}
    - COLOR=#BB28F1
    - BITCOIN_ACTIVE=y
    - BITCOIN_TESTNET=y
    - BITCOIN_NODE=bitcoind
    - BITCOIND_RPCHOST=bitcoind-testnet
    - BITCOIND_RPCUSER=${RPCUSER:-foo}
    - BITCOIND_RPCPASS=${RPCPASSWORD:-bar}
    - BITCOIND_ZMQPATH=tcp://bitcoind-testnet:28332
    - DEBUGLEVEL=info
    - EXTERNALIP=${EXTERNAL_IP:-lightning.example.com}

  lnd-web-client:
    container_name: lnd-web-client
    image: fuzzle/abc:latest
    networks:
     btc_lightning_net:
       ipv4_address: ${LND_WEB_CLIENT_IPV4:-172.19.1.130}
    environment:
      - SET_SERVERHOST=lnd-web.fuzzle.ch
      - LE_EMAIL=a.lingenhag@gmail.com
      - SET_LNDHOST=${LND_IPV4:-172.19.1.120}

    volumes:
      - 'lnd-data:/config'
    ports:
      - 8280:8280

networks:
  btc_lightning_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24

volumes:
  bitcoin-data:
  lnd-data:
