version: '2.1'
services:
  bitcoind:
    container_name: bitcoind-testnet
    image: ruimarinho/bitcoin-core:0.16.2-alpine
    networks:
      btc_lightning_net:
        ipv4_address: ${BITCOIND_IPV4:-172.19.1.110}
    volumes:
      - "${BITCOIND_DATA_PATH:-bitcoin-data}:/home/bitcoin/.bitcoin"
    command: -printtoconsole -testnet -txindex -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333 -rpcbind=0.0.0.0 -rpcallowip=${RPCALLOWIP:-172.19.1.0/24} -rpcuser=${RPCUSER:-foo} -rpcpassword=${RPCPASSWORD:-bar} -minrelaytxfee=0
    restart: "unless-stopped"

  lnd:
    container_name: lnd
    image: fuzzle/lnd-ext:latest
    networks:
      btc_lightning_net:
        ipv4_address: ${LND_IPV4:-172.19.1.120}
    ports:
      - 9735:9735
    volumes:
      - "${LND_DATA_PATH:-lnd-data}:/root/.lnd"
    environment:
    - NOENCRYPTWALLET=y
    - ALIAS=${ALIAS}
    - COLOR=#BB28F1
    - BITCOIN_ACTIVE=y
    - BITCOIN_TESTNET=y
    - BITCOIN_NODE=bitcoind
    - BITCOIND_RPCHOST=bitcoind-testnet
    - BITCOIND_RPCUSER=${RPCUSER:-foo}
    - BITCOIND_RPCPASS=${RPCPASSWORD:-bar}
    - BITCOIND_ZMQPUBRAWBLOCK=tcp://bitcoind-testnet:28332
    - BITCOIND_ZMQPUBRAWTX=tcp://bitcoind-testnet:28333
    - DEBUGLEVEL=info
    - EXTERNALIP=${EXTERNAL_IP:-lightning.example.com}
    - RESTLISTEN=0.0.0.0:8080
    - RPCLISTEN=0.0.0.0:10009
    - TLSEXTRADOMAIN=lnd
    #- AUTOPILOT_ACTIVE=n
    #- AUTOPILOT_ALLOCATION=0.9
    #- AUTOPILOT_MINCHANSIZE=10
    #- AUTOPILOT_MAXCHANSIZE=50
  lnd-gui:
    container_name: lnd-gui
    image: fuzzle/lnd-gui:latest
    networks:
      btc_lightning_net:
        ipv4_address: ${LNDGUI_IPV4:-172.19.1.130}
    ports:
      - 8888:80
  lnd-rest:
    container_name: lnd-rest
    image: fuzzle/lnd-rest:latest
    networks:
      btc_lightning_net:
        ipv4_address: ${LNDREST_IPV4:-172.19.1.140}
    volumes:
      - "${LND_DATA_PATH:-lnd-data}:/root/.lnd"
    environment:
      - LND_HOST=${LNDREST_LND_HOST:-lnd}
      - LND_RPC_PORT=${LNDREST_LND_PORT:-10009}
      - CERT_PATH=/root/.lnd/tls.cert
      - READONLY_MACAROON_PATH=/root/.lnd/readonly.macaroon
      - INVOICE_MACAROON_PATH=/root/.lnd/invoice.macaroon
networks:
  btc_lightning_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24

volumes:
  bitcoin-data:
  lnd-data:
